<a href="https://colab.research.google.com/github/Dis-ease-20/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the Numpy library **

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7])

In [3]:
print(arr)

[1 2 3 4 5 6 7]


In [4]:
type(arr)

numpy.ndarray

**0-D Array**

In [5]:
arr0 = np.array(45)
print(arr0)

45


**1-D Array**

In [6]:
arr1 = np.array([23,56,23,56,76])
print(arr1)

[23 56 23 56 76]


**2-D Array**

In [7]:
arr2 = np.array([[12,3,45,2,3],[12,77,4,23,32]])
print(arr2)

[[12  3 45  2  3]
 [12 77  4 23 32]]


**3-D Array**

In [8]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [9]:
#checking the dimension of array
arr0.ndim

0

In [10]:
#checking the dimension of array
arr1.ndim

1

In [11]:
#checking the dimension of array
arr2.ndim

2

In [12]:
#creating the array of n-dim
arr = np.array([1,2,3,4], ndmin=6)
print(arr)
print("No. of Dimensions: ",arr.ndim)

[[[[[[1 2 3 4]]]]]]
No. of Dimensions:  6


**Accessing Element**

In [14]:
print(arr0)

print(arr1[0])

print(arr2[1,1])

print(arr3[0,0,-1])

45
23
77
3


**Shape of array**

In [19]:
arr = np.array([[1,5,8,34,889],[12,56,33,90,34]])
arr_len = arr.shape
print(arr_len)

(2, 5)


**Data Types**

In [21]:
arr = np.array(['apple','banana','cherry'])

print(arr.dtype)

<U6


In [24]:
arr = np.array([1,2,3,4], dtype='int8')  #int8, int16, int 32
print(arr)
print(arr.dtype)

[1 2 3 4]
int8


In [28]:
arr = np.array([1.3,4.2,6.7])
print(arr)
print(arr.dtype)

newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1.3 4.2 6.7]
float64
[1 4 6]
int64


**Copy & View**

In [29]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
x[0] = 42

print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


In [30]:
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


**Reshaping Array**

In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr= arr.reshape(3,3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
arr = np.array([1,2,3,4,5,6,7,8,9,3,4,1])
newarr= arr.reshape(2,2,3)

print(newarr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 4 1]]]


In [35]:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


**Concatenate**

In [43]:
arr1 = np.array([1, 4 ,8 , 9])
arr2 = np.array([2, 3, 5, 0])
arr = np.concatenate((arr1,arr2), axis=0)
print(arr)

[1 4 8 9 2 3 5 0]


In [45]:
arr1 = np.array([[1, 4 ,8 , 9], [12,4,56,23]])
arr2 = np.array([[2, 3, 5, 0], [11,22,33,44]])
arr = np.concatenate((arr1,arr2), axis=1)
print(arr)

[[ 1  4  8  9  2  3  5  0]
 [12  4 56 23 11 22 33 44]]


**Stacking**

In [46]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [47]:
# Horizontal Stacking

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [48]:
# Horizontal Stacking

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


**Assignment  -- Display the content of list as count of each element in  the form of Dictionary. **

In [49]:
a=[10,12,11,12,13,10]
b=[1,2,6,2,47,85,2,45,2,1]

s1 = set(a)
s2 = set(b)
print(s1)
print(s2)

{10, 11, 12, 13}
{1, 2, 6, 45, 47, 85}


In [50]:
A_list=[]
for i in s1:
    A_list.append((i, a.count(i)))

print(A_list)

B_list=[]
for i in s2:
    B_list.append((i, b.count(i)))

print(B_list)

[(10, 2), (11, 1), (12, 2), (13, 1)]
[(1, 2), (2, 4), (6, 1), (45, 1), (47, 1), (85, 1)]


In [51]:
d={}
d["List A"]=A_list
d["List B"]=B_list
d

{'List A': [(10, 2), (11, 1), (12, 2), (13, 1)],
 'List B': [(1, 2), (2, 4), (6, 1), (45, 1), (47, 1), (85, 1)]}